services:
  postgres:
    image: postgres:16-alpine
    container_name: exomarket-postgres
    environment:
      POSTGRES_DB: exomarket_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: exomarket-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_API_CORS_ALLOW_ORIGIN: "http://localhost:3000,http://localhost:5173"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  minio-init:
    image: quay.io/minio/mc:RELEASE.2025-08-13T08-35-41Z
    container_name: exomarket-minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      set -e;
      until mc alias set local http://minio:9000 minioadmin minioadmin; do sleep 2; done;
      mc mb --ignore-existing local/exocad-cases;
      mc anonymous set none local/exocad-cases;
      mc mb --ignore-existing local/profile-avatars;
      mc anonymous set download local/profile-avatars;
      "

volumes:
  pgdata:
  miniodata:
