version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: exomarket-postgres
    environment:
      POSTGRES_DB: exomarket_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: